<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy for PomoTick: Pomodoro Timer</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <style>
        body { max-width: 800px; margin: 40px auto; background: #fff; color: #222; font-family: 'Sora', sans-serif; padding: 2rem; border-radius: 12px; box-shadow: 0 2px 16px rgba(0,0,0,0.07); }
        h1, h2, h3 { color: #000; }
        @media (max-width: 900px) { body { margin: 0; border-radius: 0; box-shadow: none; padding: 1rem; } }
    </style>
</head>
<body>
<main>
<h1>Privacy Policy for PomoTick: Pomodoro Timer</h1>
<p><strong>Last updated: June 2024</strong></p>
<p>This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>Words with capitalized initial letters have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
<h3>Definitions</h3>
<ul>
<li><strong>Application</strong> refers to PomoTick: Pomodoro Timer.</li>
<li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PomoTick.</li>
<li><strong>Country</strong> refers to Turkey.</li>
<li><strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or digital tablet.</li>
<li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
<li><strong>Service</strong> refers to the Application.</li>
<li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
<li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
<li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
</ul>
<h2>Collecting and Using Your Personal Data</h2>
<h3>Types of Data Collected</h3>
<h4>Personal Data</h4>
<p>PomoTick does not collect or require any personally identifiable information from users. No name, email, phone number, or similar data is collected.</p>
<h4>Usage Data</h4>
<p>PomoTick does not collect any usage data or analytics. All data and settings remain on your device and are not transmitted to any server.</p>
<h3>Use of Your Personal Data</h3>
<p>Since PomoTick does not collect any personal data, your information is never used, shared, or sold to third parties.</p>
<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.</p>
<h2>Links to Other Websites</h2>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h2>Changes to this Privacy Policy</h2>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>By email: sametyesilotiletisim@gmail.com</li>
</ul>
<p><strong>Last updated: June 2024</strong></p>
</main>
</body>
</html>
